package day42_Exceptions;

public class ThrowsKeyword2 {


    public static void main(String[] args) throws ArithmeticException {
// metod syntax ına yazarsan SADECE METOD İÇİNDE HATAYI BERTARAF EDER
        System.out.println("Test started");

        System.out.println(8/0);

        System.out.println("Test completed");


    }
}
